### ISSUE TITLE
Merge branch in into master & update style guide to use valid syntax

### ISSUE THREAD

**Issue by ChrisMBarr** [artandlogic/eslint-config-artandlogic#1]
I am being asked to complete a programming challenge for Art+Logic, and [the linting page of the Art+Logic style guide](https://styleguide.artandlogic.com/linting) says I should run the following command:
```
npm install --save-dev eslint https://github.com/artandlogic/eslint-config-artandlogic
```
Which results in the following error:
```
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\chris\AppData\Local\npm-cache\_cacache\tmp\git-clonet67kof/package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\chris\AppData\Local\npm-cache\_cacache\tmp\git-clonet67kof\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\chris\AppData\Local\npm-cache\_logs\2023-09-13T18_38_31_192Z-debug-0.log
```

This is due to two issues:

## Issue #1: Incorrect NPM syntax
The style guide recommends using  incorrect syntax for installing a package from a git repository
It should instead be written as:
```
npm install --save-dev git+https://github.com/artandlogic/eslint-config-artandlogic.git
```

## Issue #2: The git repo in that URL has no code!
This repo only has a license and a readme file, no code at all!  There is a [`phendry/wip` branch](https://github.com/artandlogic/eslint-config-artandlogic/tree/phendry/wip) which does have a [lint config file](https://github.com/artandlogic/eslint-config-artandlogic/blob/phendry/wip/.eslintrc.js). However this is not what the style guide says to do.

If the `phendry/wip` branch were to be merged into master and then the style guide updated to address issue #1 above, then the guide could be followed as written

## Workaround for now
For the time being I can install this git repo at a specific branch using this command
```
npm install --save-dev git+https://github.com/artandlogic/eslint-config-artandlogic.git#phendry/wip
```

**Comment by phendry-artlogic** [comment]
Oops, yes that branch ought to have been merged. The `main` branch now contains the up-to-date ESLint config, and the docs have been updated with the correct `git+` URL. Thanks for the detailed report!
